config/routes.rb
Pagpos::Application.routes.draw do
  get "statistics/index"
  get "packages/index"
  post "subscriber/create" => "subscribers#create"
  get "store_metadatas/create"
  get "store_metadatas/update"
  get "newsletters/index"
  get "sms/index"
  get "stores/index"
  get "stores/dashboard"
  get 'trackings' => 'trackings#new', as: 'new_tracking'
  get 'tracking/:code/:token' => 'trackings#show', as: 'tracking'
  post 'trackings' => 'trackings#create'
  delete 'tracking/:code/:token' => 'trackings#destroy'

  get 'subscriber' => "welcome#index"
  get 'welcome' => "pagpos#new2"

  get 'about' => 'welcome#about'

  get 'pagpos' => "pagpos#new"
  post 'pagpos' => "pagpos#create"
  get 'pagpos/:code' => "pagpos#show" #, as: "pagpos_result"

  get 'pagpos2' => "pagpos#new2"

  devise_for :users, :controllers => {
    :omniauth_callbacks => "omniauth_callbacks",
    :sessions => "sessions",
    :passwords => "passwords",
    :registrations => "stores"
  }
  # get 'users/auth/facebook' => 'omniauth_callbacks#passthru'
  # get 'users/auth/google' => 'omniauth_callbacks#passthru'
  # get 'users/auth/twitter' => 'omniauth_callbacks#passthru'

  get 'templates' => 'welcome#templates'

  get 'user_agreement' => 'welcome#user_agreement'
  get 'privacy' => 'welcome#privacy'

  devise_scope :user do
    # root to: 'devise/sessions#new'
    # root to: 'welcome#index'
    root to: 'pagpos#new2'
    get 'users' => "users#index"
    put 'users/:id' => 'users#update', as: 'user_update'
    get 'user_profile' => 'users#edit'
    get 'users/auth/:provider' => 'omniauth_callbacks#passthru'

    get 'send_fbchat' => 'api/v1/pagpos#fbchat'

    # namespace :store do
    #   root to: redirect(path: '/store/dashboard')
    #   get 'dashboard' => 'dashboards#index'
    #   get 'sms', shallow: true
    # end

    # namespace :admin do
    #   root to: redirect(path: '/admin/dashboard')
    #   get 'dashboard' => 'dashboard#index'
    # end

    scope shallow_path: "store" do
      get 'store' => redirect(path: '/store/dashboard'), as: 'stores_root'
      get 'store/dashboard' => 'stores#dashboard'
      get 'store/login' => 'stores#index'
      get 'store/register' => 'stores#register'
      post 'store/register' => 'stores#create'
      get 'store/recovery_password' => 'stores#forgot_password'

      get 'store/profile' => 'stores#profile'
      get 'store/profile/:user_id' => 'stores#profile', as: 'store_profile_with'
      patch 'store/profile' => 'stores#update_profile'
      get 'store/lists' => 'stores#list'

      get 'store/sms/packages' => 'sms#packages', as: 'store_campaigns'
      post 'store/sms/packages/(:id)/buy' => 'sms#buy_package', as: 'store_buy_package'
      get 'store/sms/packages/get_free_package' => 'sms#get_free_package', as: 'store_get_free_package'
      # post 'store/sms/packages/(:id)/paid' => 'sms#paid_package', as: 'store_paid_package'
      get 'store/sms/(:filter)' => 'sms#index', as: 'store_sms'
      get 'store/newsletters' => 'newsletters#index'

      get 'store/sms/buy_package/test/callback' => 'sms#buy_package_callback', as: 'store_buy_package_test_callback'
      get 'store/sms/buy_package/live/callback' => 'sms#buy_package_callback', as: 'store_buy_package_live_callback'

      get 'store/customers' => 'users#customer'
      get 'store/add_customer' => 'users#add_customer'
      get 'store/customer/:id' => 'users#detail_customer', as: 'store_customer'
      delete 'store/customer/:id' => 'users#destroy_customer'
      get 'store/customer/:id/edit' => 'users#edit_customer', as: 'store_edit_customer'
      post 'store/customer' => 'users#create_customer'
      patch 'store/customer/:id' => 'users#update_customer'

      get 'store/users' => 'users#user'
      get 'store/packages' => 'packages#index'
      get 'store/statistics' => 'statistics#index'
      get 'store/invoices' => 'pag_invoices#index'
      get 'store/invoices/:payment_code' => 'pag_invoices#show', as: 'store_invoice'
      delete 'store/invoices/:payment_code' => 'pag_invoices#destroy'
    end

  end

  namespace :api do
    namespace :v1  do
      devise_for :users
      root to: 'welcome#index'

      # Trackings always send :code and :token
      get 'trackings/:code/:token' => 'trackings#show', as: 'trackings'
      post 'trackings' => 'trackings#create'
      delete 'trackings' => 'tracking#destroy'

      get 'force_get_data' => 'pagpos#force_get_data'
      get 'show' => 'pagpos#show'
      # get 'auth/:provider' => 'omniauth_callbacks#passthru'
      # get 'auth/facebook' => 'omniauth_callbacks#passthru'
      # get 'auth/google' => 'omniauth_callbacks#passthru'
      # get 'auth/twitter' => 'omniauth_callbacks#passthru'
    end
  end

  mount Resque::Server, :at => "/resque"
  # authenticate :user do
    # mount Resque::Server, :at => "/resque"
  # end


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/store/stores_controller.rb
class Store::StoresController < Devise::RegistrationsController
  before_filter :require_merchant, except: [:index]
  layout 'backend'

	def resource_name
    :user
  end

  def resource
    @resource ||= User.new
  end

  def devise_mapping
    @devise_mapping ||= Devise.mappings[:user]
  end

  def index
    redirect_to store_root_path if current_user.present?
  end

  def new
  end

  def create
  end

  def lists
  end
end

app/controllers/stores_controller.rb
class StoresController < Devise::RegistrationsController
  before_filter :require_merchant, except: [:index, :register, :create, :forgot_password]
  before_filter :permitt_parameters, only: [:create, :update_profile]
  layout 'backend'

  def resource_name
    :user
  end

  def resource
    resource ||= User.new
  end

  def devise_mapping
    devise_mapping ||= Devise.mappings[:user]
  end

  def index
    redirect_to stores_root_path if current_user.present? && current_user.has_any_role?(:merchant, :god)
  end

  def dashboard
    @page_title = I18n.t('backend.menu.dashboard')
  end

  def list
  end

  def register
  end

  def create
    resource = build_resource(sign_up_params)

    if resource.save
      # resource.roles.create(name: 'merchant', resource_type: 'merchant', resource_id: resource.id)
      resource.add_role :merchant

      # Comment out if add UserMailer arleady
      # UserMailer.welcome(resource).deliver unless resource.invalid?

      if resource.active_for_authentication?
        set_flash_message :notice, :signed_up if is_navigational_format?
        sign_in(resource_name, resource)
        return redirect_to store_profile_path
      else
        set_flash_message :notice, :"signed_up_but_#{resource.inactive_message}" if is_navigational_format?
        expire_session_data_after_sign_in!
        return redirect_to action: :index
      end
    else
      clean_up_passwords resource
      flash[:error] = resource.errors.full_messages
      render :register
    end
  end

  def forgot_password
  end

  def profile
    @page_title = 'Profile details'
    user_id = params[:user_id].present? ? params[:user_id] : current_user.id
    @user = User.where(id: user_id).first
    @user.build_store_detail if @user.store_detail.blank?
  end

  def update_profile
    user_id = params[:user][:user_id].present? ? params[:user][:user_id] : current_user.id
    @user = User.where(id: user_id).first
    update_result = if params[:user][:password].blank?
      params[:user].delete('current_password')
      @user.update_without_password(account_update_params)
    else
      @user.update_with_password(account_update_params)
    end
    # debugger
    if update_result
      set_flash_message :success, :updated
      sign_in resource_name, current_user
      redirect_to store_profile_with_path(user_id)
    else
      clean_up_passwords current_user
      render :profile
    end
  end

  private
    def permitt_parameters
      devise_parameter_sanitizer.for(:sign_up) do |u|
        u.permit(:email, :password, :password_confirmation, :time_zone, :roles, roles_attributes: [:id, :name])
      end

      devise_parameter_sanitizer.for(:account_update) do |u|
        u.permit(:password, :password_confirmation, :current_password, :email, :reminder_when, :reminder_by, :phone_no, :name, :gender, :time_zone, store_detail_attributes: [:id, :name, :phone1, :phone2, :description, :address, :city, :district, :province, :postal_code, :email])
      end
    end
end

app/views/stores/dashboard.html.haml
.row

app/views/stores/forgot_password.html.haml
.container
  .row
    .col-md-3.col-md-offset-5
      .login-panel.panel.panel-default
        .panel-heading
          = image_tag('logos.png', width: 250)
        .panel-body
          = simple_form_for(resource, :as => resource_name, :url => password_path(resource_name), :html => { :method => :post }) do |f|
            %h2.center-block.text-center= t("forgot_password.title")
            %fieldset
              .form-group
                = f.input :email, :required => true, :autofocus => true, placeholder: t('forgot_password.hint'), input_html: { class: 'form-control'}
              = f.button :submit, t("forgot_password.submit_btn"), :class => 'btn btn-lg btn-block btn-primary'
              %br
              %p.signup.center-block.text-center
                = t("signin.description")
                = link_to t("signin.title"), store_login_url, class: 'text-primary'

app/views/stores/index.html.haml
.container
  .row
    .col-md-3.col-md-offset-5
      .login-panel.panel.panel-default
        .panel-heading
          = link_to(image_tag('logos.png', width: 250), root_path)
        .panel-body
          = simple_form_for(resource, :as => resource_name, :url => session_path(resource_name), :defaults => {:wrapper_html => {:class => 'form-group'}}) do |f|
            = f.error_notification
            %h2.text-center=t('signin.title')
            %fieldset
              .form-group
                = f.input :email, :required => true, :autofocus => true, :input_html => { :class => 'form-control' }
              .form-group
                = f.input :password, :required => true, :input_html => { :class => 'form-control' }
              = link_to t('forgot_password.title'), store_recovery_password_url, class: 'pull-right'
              = f.input :remember_me, inline_label: t('signin.remember_me'), label: false, :as => :boolean if devise_mapping.rememberable?
              = f.button :submit, t('signin.submit_btn'), :class => 'btn btn-lg btn-block btn-primary'
              %br
              %p.signup.center-block.text-center
                = t("signup.description")
                = link_to t("signup.title"), store_register_url, class: 'text-primary'

app/views/stores/list.html.haml
.row

app/views/stores/profile.html.haml
.row
  .col-lg-12
    .col-lg-3 &nbsp;
    .col-lg-6
      = simple_form_for(@user, :as => resource_name, :url => store_profile_path, :html => { :method => :patch, role: 'form' }) do |f|
        %fieldset
          %legend ความปลอดภัย
          .form-group
            = f.error_notification
          .form-group
            = f.label :password, "รหัสผ่าน"
            = f.input :password, :autofocus => true, label: false, :input_html => { class: 'form-control' }
          .form-group
            = f.label :password_confirmation, "ยืนยันรหัสผ่านอีกครั้ง"
            = f.input :password_confirmation, label: false, :input_html => { class: 'form-control' }
          .form-group
            = f.label :current_password, "รหัสผ่านปัจจุบัน"
            = f.input :current_password, :hint => "we need your current password to confirm your changes", label: false, :input_html => { class: 'form-control' }
        %br
        %fieldset
          %legend ข้อมูลร้านค้า/บริษัท
          = f.fields_for :store_detail do |m|
            .form-group
              = m.label :name, "ชื่อร้านค้า/บริษัท"
              = m.input :name, required: true, label: false, input_html: { class: 'form-control' }
            .form-group
              = m.label :phone1, "เบอร์โทัศัพท์ 1"
              = m.input :phone1, required: true, label: false, input_html: { class: 'form-control' }
            .form-group
              = m.label :phone2, "เบอร์โทัศัพท์ 2"
              = m.input :phone2, required: false, label: false, input_html: { class: 'form-control' }
            .form-group
              = m.label :description, "รายละเอียดเพิ่มเติม"
              = m.input :description, required: false, label: false, as: :text, input_html: { class: 'form-control' }
            .form-group
              = m.label :address, "ที่อยู่"
              = m.input :address, required: true, label: false, input_html: { class: 'form-control' }
            .form-group
              = m.label :city, "ตำบล/แขวง"
              = m.input :city, required: true, label: false, input_html: { class: 'form-control' }
            .form-group
              = m.label :district, "อำเภอ/เขต"
              = m.input :district, required: true, label: false, input_html: { class: 'form-control' }
            .form-group
              = m.label :province, "จังหวัด"
              = m.input :province, required: true, label: false, input_html: { class: 'form-control' }
            .form-group
              = m.label :postal_code, "รหัสไปรษณีย์"
              = m.input :postal_code, required: true, label: false, input_html: { class: 'form-control' }
            .form-group
              = m.label :email, "อีเมล"
              = m.input :email, required: true, label: false, input_html: { class: 'form-control' }
          = f.hidden_field :user_id, value: params[:user_id]
        = f.submit 'บันทึก', class: 'button btn btn-primary btn-lg col-lg-12'
    .col-lg-3 &nbsp;

app/views/stores/register.html.haml
.container
  .row
    .col-md-3.col-md-offset-5
      .login-panel.panel.panel-default
        .panel-heading
          = image_tag('logos.png', width: 250)
        .panel-body
          = simple_form_for(resource, :as => resource_name, :url => store_register_path, :defaults => {:wrapper_html => {:class => 'form-group'}}) do |f|
            = devise_error_messages!
            = f.error_notification
            %h2.text-center=t('signup.title')
            %fieldset
              .form-group
                = f.error :email
                = f.input :email, :required => true, :autofocus => true, :input_html => { :class => 'form-control' }
              .form-group
                = f.error :password
                = f.input :password, :required => true, :input_html => { :class => 'form-control' }
              .form-group
                = f.error :password_confirmation
                = f.input :password_confirmation, :required => true, :input_html => { :class => 'form-control' }
              = f.hidden_field :time_zone, value: DateTime.now.zone.to_i

              = f.button :submit, t('signup.submit_btn'), :class => 'btn btn-lg btn-block btn-primary'
              %br
              %p.signup.center-block.text-center
                = t("signin.description")
                = link_to t("signin.title"), store_login_url, class: 'text-primary'