config/routes.rb
Pagpos::Application.routes.draw do
  get "statistics/index"
  get "packages/index"
  post "subscriber/create" => "subscribers#create"
  get "store_metadatas/create"
  get "store_metadatas/update"
  get "newsletters/index"
  get "sms/index"
  get "stores/index"
  get "stores/dashboard"
  get 'trackings' => 'trackings#new', as: 'new_tracking'
  get 'tracking/:code/:token' => 'trackings#show', as: 'tracking'
  post 'trackings' => 'trackings#create'
  delete 'tracking/:code/:token' => 'trackings#destroy'

  get 'subscriber' => "welcome#index"
  get 'welcome' => "pagpos#new2"

  get 'about' => 'welcome#about'

  get 'pagpos' => "pagpos#new"
  post 'pagpos' => "pagpos#create"
  get 'pagpos/:code' => "pagpos#show" #, as: "pagpos_result"

  get 'pagpos2' => "pagpos#new2"

  devise_for :users, :controllers => {
    :omniauth_callbacks => "omniauth_callbacks",
    :sessions => "sessions",
    :passwords => "passwords",
    :registrations => "stores"
  }
  # get 'users/auth/facebook' => 'omniauth_callbacks#passthru'
  # get 'users/auth/google' => 'omniauth_callbacks#passthru'
  # get 'users/auth/twitter' => 'omniauth_callbacks#passthru'

  get 'templates' => 'welcome#templates'

  get 'user_agreement' => 'welcome#user_agreement'
  get 'privacy' => 'welcome#privacy'

  devise_scope :user do
    # root to: 'devise/sessions#new'
    # root to: 'welcome#index'
    root to: 'pagpos#new2'
    get 'users' => "users#index"
    put 'users/:id' => 'users#update', as: 'user_update'
    get 'user_profile' => 'users#edit'
    get 'users/auth/:provider' => 'omniauth_callbacks#passthru'

    get 'send_fbchat' => 'api/v1/pagpos#fbchat'

    # namespace :store do
    #   root to: redirect(path: '/store/dashboard')
    #   get 'dashboard' => 'dashboards#index'
    #   get 'sms', shallow: true
    # end

    # namespace :admin do
    #   root to: redirect(path: '/admin/dashboard')
    #   get 'dashboard' => 'dashboard#index'
    # end

    scope shallow_path: "store" do
      get 'store' => redirect(path: '/store/dashboard'), as: 'stores_root'
      get 'store/dashboard' => 'stores#dashboard'
      get 'store/login' => 'stores#index'
      get 'store/register' => 'stores#register'
      post 'store/register' => 'stores#create'
      get 'store/recovery_password' => 'stores#forgot_password'

      get 'store/profile' => 'stores#profile'
      get 'store/profile/:user_id' => 'stores#profile', as: 'store_profile_with'
      patch 'store/profile' => 'stores#update_profile'
      get 'store/lists' => 'stores#list'

      get 'store/sms/packages' => 'sms#packages', as: 'store_campaigns'
      post 'store/sms/packages/(:id)/buy' => 'sms#buy_package', as: 'store_buy_package'
      get 'store/sms/packages/get_free_package' => 'sms#get_free_package', as: 'store_get_free_package'
      # post 'store/sms/packages/(:id)/paid' => 'sms#paid_package', as: 'store_paid_package'
      get 'store/sms/(:filter)' => 'sms#index', as: 'store_sms'
      get 'store/newsletters' => 'newsletters#index'

      get 'store/sms/buy_package/test/callback' => 'sms#buy_package_callback', as: 'store_buy_package_test_callback'
      get 'store/sms/buy_package/live/callback' => 'sms#buy_package_callback', as: 'store_buy_package_live_callback'

      get 'store/customers' => 'users#customer'
      get 'store/add_customer' => 'users#add_customer'
      get 'store/customer/:id' => 'users#detail_customer', as: 'store_customer'
      delete 'store/customer/:id' => 'users#destroy_customer'
      get 'store/customer/:id/edit' => 'users#edit_customer', as: 'store_edit_customer'
      post 'store/customer' => 'users#create_customer'
      patch 'store/customer/:id' => 'users#update_customer'

      get 'store/users' => 'users#user'
      get 'store/packages' => 'packages#index'
      get 'store/statistics' => 'statistics#index'
      get 'store/invoices' => 'pag_invoices#index'
      get 'store/invoices/:payment_code' => 'pag_invoices#show', as: 'store_invoice'
      delete 'store/invoices/:payment_code' => 'pag_invoices#destroy'
    end

  end

  namespace :api do
    namespace :v1  do
      devise_for :users
      root to: 'welcome#index'

      # Trackings always send :code and :token
      get 'trackings/:code/:token' => 'trackings#show', as: 'trackings'
      post 'trackings' => 'trackings#create'
      delete 'trackings' => 'tracking#destroy'

      get 'force_get_data' => 'pagpos#force_get_data'
      get 'show' => 'pagpos#show'
      # get 'auth/:provider' => 'omniauth_callbacks#passthru'
      # get 'auth/facebook' => 'omniauth_callbacks#passthru'
      # get 'auth/google' => 'omniauth_callbacks#passthru'
      # get 'auth/twitter' => 'omniauth_callbacks#passthru'
    end
  end

  mount Resque::Server, :at => "/resque"
  # authenticate :user do
    # mount Resque::Server, :at => "/resque"
  # end


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/models/user.rb
class User
  include Mongoid::Document
  include Mongoid::Timestamps
  rolify

  has_many :trackings
  embeds_one :store_detail
  accepts_nested_attributes_for :store_detail, allow_destroy: true

  has_and_belongs_to_many :customers, :class_name => 'User', :inverse_of => :merchants
  has_and_belongs_to_many :merchants, :class_name => 'User', :inverse_of => :customers

  has_many :campaigns_users
  has_many :pag_invoices
  validates :phone_no, presence: true, :if => "reminder_by.eql?('sms')", :format => { with: /\A[0]/ }

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable,
         :omniauthable, :timeoutable

  field :name, :type => String, :default => ""

  ## Database authenticatable
  field :email,              :type => String, :default => ""
  field :encrypted_password, :type => String, :default => ""

  ## Recoverable
  field :reset_password_token,   :type => String
  field :reset_password_sent_at, :type => Time

  ## Rememberable
  field :remember_created_at, :type => Time

  ## Reminder
  field :reminder_when, :type => String, :default => "status_change"
  field :reminder_by, :type => String, :default => "email"

  field :time_zone, :type => String, :default => 0

  field :provider, :type => String
  field :uid, :type => String
  field :token_fb, :type => String

  field :specific_department, :type => String

  field :gender, :type => String, :default => ""
  field :phone_no, :type => String, :default => ""

  ## Trackable
  field :sign_in_count,      :type => Integer, :default => 0
  field :current_sign_in_at, :type => Time
  field :last_sign_in_at,    :type => Time
  field :current_sign_in_ip, :type => String
  field :last_sign_in_ip,    :type => String

  ## Confirmable
  field :confirmation_token,   :type => String
  field :confirmed_at,         :type => Time
  field :confirmation_sent_at, :type => Time
  field :unconfirmed_email,    :type => String # Only if using reconfirmable

  ## Lockable
  # field :failed_attempts, :type => Integer, :default => 0 # Only if lock strategy is :failed_attempts
  # field :unlock_token,    :type => String # Only if unlock strategy is :email or :both
  # field :locked_at,       :type => Time

  def self.find_for_facebook_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.info.email).first
      if registered_user
        registered_user.update_attributes(token_fb: auth.credentials.token)
        return registered_user
      else
        user = User.create( token_fb:auth.credentials.token,
                            name:auth.extra.raw_info.name,
                            provider:auth.provider,
                            uid:auth.uid,
                            email:auth.info.email,
                            password:Devise.friendly_token[0,20],
                            time_zone: auth.extra.raw_info.timezone,
                            gender: auth.extra.raw_info.gender
                          )
        user.add_role :user
      end

    end
  end

  def self.find_for_google_oauth2(access_token, signed_in_resource=nil)
    data = access_token.info
    user = User.where(:provider => access_token.provider, :uid => access_token.uid ).first
    if user
      return user
    else
      registered_user = User.where(:email => access_token.info.email).first
      if registered_user
        return registered_user
      else
        user = User.create(name: data["name"],
          provider:access_token.provider,
          email: data["email"],
          uid: access_token.uid ,
          password: Devise.friendly_token[0,20],
        )
      end
    end
  end

  def self.find_for_twitter_oauth(auth, signed_in_resource=nil)
    user = User.where(:provider => auth.provider, :uid => auth.uid).first
    if user
      return user
    else
      registered_user = User.where(:email => auth.uid + "@twitter.com").first
      if registered_user
        return registered_user
      else
        user = User.create(name:auth.info.name,
          provider:auth.provider,
          uid:auth.uid,
          email:auth.uid+"@twitter.com",
          password:Devise.friendly_token[0,20],
        )
      end
    end
  end
end

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  before_filter :authenticate_user!
  before_filter :require_merchant, only: [:customer, :add_customer]
  before_filter :require_admin, only: [:user]

  layout 'backend', only: [:customer, :user, :add_customer, :edit_customer, :detail_customer, :create_customer, :update_customer, :destroy_customer]

  def index
  end

  def edit
    @user = current_user
  end

  def update
    prev_unconfirmed_email = resource.unconfirmed_email if resource.respond_to?(:unconfirmed_email)
    update_result = if params[:user][:password].blank?
      params[:user].delete('current_password')
      resource.update_without_password(account_update_params)
    else
      resource.update_with_password(account_update_params)
    end
    if update_result
      if is_navigational_format?
        update_needs_confirmation?(resource, prev_unconfirmed_email)
      end
      set_flash_message :notice, :updated
      sign_in resource_name, resource
      return render 'edit'
    else
      clean_up_passwords resource
      return render 'edit'
    end
  end

  def profile
  end

  def customer
    params ||= {}
    @page_title = I18n.t('page_title.customers')
    page = params[:page].present? ? params[:page] : 1
    @users = current_user.customers.paginate(:page => page, :per_page => 20)
  end

  def user
    params ||= {}
    page = params[:page].present? ? params[:page] : 1
    @users = User.paginate(:page => page, :per_page => 20)
  end

  def detail_customer
    page = params[:page].present? ? params[:page] : 1
    @page_title = I18n.t('page_title.detail_customer')
    @user = User.where(_id: params[:id]).first
    @user_trackings = @user.trackings.paginate(:page => page, :per_page => 20)
    @tracking = @user.trackings.new
  end

  def add_customer
    @page_title = I18n.t('page_title.add_customer')
    @user = User.new
  end

  def edit_customer
    @page_title = I18n.t('page_title.edit_customer')
    @user = User.where(_id: params[:id]).first
    @user.email = nil if @user.email.scan('@pagpos.com')
  end

  def create_customer
    password = Devise.friendly_token
    params[:user][:email] = "#{params[:user][:phone_no]}@pagpos.com" if params[:user][:email].blank?
    params[:user][:password] = password
    params[:user][:password_confirmation] = password

    @user = current_user.customers.new(customer_params)

    if @user.save
      flash[:success] = I18n.t('user.add_customer.success')
      return redirect_to store_customers_url(@user.id)
    else
      render action: :add_customer
    end
  end

  def update_customer
    params[:user][:email] = "#{params[:user][:phone_no]}@pagpos.com" if params[:user][:email].blank?
    update_result = User.where(_id: params[:id]).first
    if update_result.update_attributes(account_update_params)
      flash[:success] = I18n.t('user.update_customer.success')
      return redirect_to store_customers_url
    else
      render :edit_customer
    end
  end

  def destroy_customer
    user = User.where(_id: params[:id]).first
    if user.destroy
      flash[:success] = I18n.t('user.destroy_customer.success')
    else
      flash[:error] = user.errors.full_messages
    end
    return redirect_to store_customers_url
  end

  def customer_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :phone_no, :reminder_by, :gender, :user_reminder_when)
  end

  def account_update_params
    params.require(:user).permit(:password, :password_confirmation, :current_password, :reminder_when, :reminder_by, :phone_no, :email, :name, :gender, :time_zone)
  end

end

app/views/users/_form_customer.html.haml
= simple_form_for(@user, :url => store_customer_url(@user), :html => {role: 'form' }) do |f|
  .form-group
    .large-12.columns
      = f.error_notification
      = render "shared/flash_message_backend", flash: flash
  %fieldset
    %legend ข้อมูลส่วนตัว
    .form-group
      .large-6.columns ชื่อ
      .large-6.columns
        = f.input :name, :label => false, :required => false, input_html: { class: 'form-control' }
    .form-group
      .large-6.columns อีเมล
      .large-6.columns
        = f.input :email, :label => false, :required => false, input_html: { class: 'form-control' }
    .form-group
      .large-6.columns เพศ
      .large-6.columns
        = f.input :gender, collection: {t("user.gender.male") => "male", t("user.gender.female") => "female"}, selected: @user.gender, label: false, input_html: { class: 'form-control' }
  %fieldset
    %legend การแจ้งเตือน
    .form-group
      .large-6.columns แจ้งเตือนเมื่อ
      .large-6.columns
        = f.input :reminder_when, collection: {"Status change" => "status_changed", "Specific post" => "specific_post", "Specific time" => "specific_time"}, selected: @user.reminder_when.to_sym, label: false, disabled: true, input_html: { class: 'form-control' }
    .form-group
      .large-6.columns ช่่องทางแจ้งเตือน
      .large-6.columns
        = f.input :reminder_by, collection: {"SMS" => "sms", "Email" => "email"}, selected: @user.reminder_by.to_sym, label: false, input_html: { class: 'form-control' }
    .form-group
      .large-6.columns หมายเลขโทรศัพท์
      .large-6.columns
        = f.input :phone_no, :placeholder => "0812345678", :required => false,  label: false, input_html: { class: 'form-control' }
    .form-group
      .large-12.columns
        = f.submit 'Submit', class: 'button btn btn-primary btn-lg col-lg-12'
= render "shared/required_remider"

app/views/users/add_customer.html.haml
.row
  .col-lg-12
    .col-lg-3 &nbsp;
    .col-lg-6
      = render 'form_customer', locals: { user: @user }
    .col-lg3 &nbsp;

app/views/users/customer.html.haml
.row
  .col-lg-12
    / /.panel-heading
    .panel-body
      .inbox-checkbox-triggered
        .btn-group.pull-right
          = link_to raw("<i class='glyphicon glyphicon-plus'></i> #{t('backend.add')}"), store_add_customer_url, class: 'btn btn-primary'
      .table-responsive
        %table#dataTables.table.table-striped.table-hover.dataTable
          %thead
            %tr
              %th Name
              %th Remider By
              %th Email
              %th Phone No.
              %th Item(s)
          %tbody
            - @users.each_with_index do |u, i|
              %tr{class: (i%2==0) ? 'odd' : 'even'}
                %td=u.name
                %td=u.reminder_by.upcase
                %td
                  - if u.email.scan('@pagpos.com').length.eql?(0)
                    =u.email
                %td
                  =u.phone_no
                %td
                  = u.trackings.count
                  .btn-group.display-inline.pull-right.text-align-left
                    = link_to raw("<i class='fa fa-barcode fa-lg fa-fw'></i> Tracking"), store_customer_url(u)
                    = link_to raw("<i class='fa fa-pencil fa-lg fa-fw'></i> Edit"), store_edit_customer_url(u)
                    = link_to raw("<i class='fa fa-times fa-lg fa-fw'></i> Delete"), store_customer_url(u), method: :delete, data: { confirm: "Do you really want to delete customer?" }
        / /.table-responsive
      / /.panel-body
      = will_paginate @users, :previous_label => t("will_paginate.previous"), :next_label => t("will_paginate.next"), renderer: BootstrapPagination::Rails
    / /.panel
  / /.col-lg-12
= content_for :stylesheets do
  = stylesheet_link_tag 'dataTable.bootstrap'
= content_for :javascripts do
  = javascript_include_tag 'jquery.dataTables', 'dataTable.bootstrap'

app/views/users/detail_customer.html.haml
.row
  .col-lg-12
    .col-lg-3 &nbsp;
    .col-lg-6
      = simple_form_for(@tracking, :url => trackings_path(@tracking), :html => { :method => :post, class: 'custom' }) do |f|
        = f.error_notification
        = hidden_field_tag :token, params[:id]
        .row
          .form-group
            = f.input :code, :label => false, :required => false, placeholder: t('trackings.placeholder_tracking_id'), input_html: { class: 'form-control' }
          .form-group
            = f.input :token, :as => :hidden, input_html: { value: @user._id }
            = f.submit t('trackings.track_btn'), class: 'button btn btn-primary btn-lg col-lg-12'
    .col-lg3 &nbsp;
%br
%br
.row
  .col-lg-12
    .col-lg-3 &nbsp;
    .col-lg-6
      .table-responsive
        %table#dataTables.table.table-striped.table-hover.dataTable.no-margin
          %thead
            %tr
              %th{width: "140"}= t('trackings.tracking_code')
              %th{width: "100"}= t('trackings.status')
              %th{width: "200"}
          %tbody
          - @user_trackings.each_with_index do |t, i|
            %tr{class: (i%2==0) ? 'odd' : 'even'}
              %td= t.code
              %td
                - status = t.status == 'done' ? 'label-success' : t.status == 'pending' ? 'label-default' : 'label-danger'
                %span{class: "#{status} radius label"}= t("tracking_status.#{t.status}")
              %td
                .btn-group.display-inline.pull-right.text-align-left
                  = link_to raw("<i class='glyphicon glyphicon-info-sign'></i> #{t("trackings.details_btn")}"), tracking_path(t.code, @user.id), class: 'button', disabled: status == 'alert' ? true : false
                  = link_to raw("<i class='glyphicon glyphicon-remove-sign'></i> #{t("trackings.delete_btn")}"), tracking_path(t.code, @user.id), class: 'button', method: :delete, :confirm => t('trackings.delete_confirmation')
      = will_paginate @user_trackings, :previous_label => t("will_paginate.previous"), :next_label => t("will_paginate.next"), renderer: BootstrapPagination::Rails
    .col-lg-3 &nbsp;

= content_for :stylesheets do
  = stylesheet_link_tag 'dataTable.bootstrap'
= content_for :javascripts do
  = javascript_include_tag 'jquery.dataTables', 'dataTable.bootstrap'

:javascript
  $(document).ready(function(){
    if($('#dataTables tbody').length > 1){
      $('#dataTables tbody').first().remove();
    }
  });

app/views/users/edit.html.haml
.row
  .large-12.columns
    .large-3.columns &nbsp;
    .large-6.columns
      = simple_form_for(@user, :url => user_update_path(@user), :html => { :method => :put, class: 'custom' }) do |f|
        .row
          .large-12.columns
            = f.error_notification
            = render "shared/flash_message", flash: flash
        - if @user.provider.blank?
          %h4 ความปลอดภัย
          .row
            = f.input :reset_password_token, :as => :hidden
            = f.full_error :reset_password_token
            .large-6.columns รหัสผ่าน
            .large-6.columns
              = f.input :password, :label => "New password", :required => true, :autofocus => true, label: false
          .row
            .large-6.columns ยืนยันรหัสผ่านอีกครั้ง
            .large-6.columns
              = f.input :password_confirmation, :label => "Confirm your new password", :required => true, label: false
          .row
            .large-6.columns รหัสผ่านปัจจุบัน
            .large-6.columns
              = f.input :current_password, :hint => "we need your current password to confirm your changes", label: false
        %h4 ข้อมูลส่วนตัว
        .row
          .large-6.columns ชื่อ
          .large-6.columns
            = f.input :name, :label => false, :required => true
        .row
          .large-6.columns อีเมล
          .large-6.columns
            = f.input :email, :label => false, :required => true
        .row
          .large-6.columns เพศ
          .large-6.columns
            = f.input :gender, collection: {t("user.gender.male") => "male", t("user.gender.female") => "female"}, selected: @user.gender, label: false
        %h4 การแจ้งเตือน
        .row
          .large-6.columns แจ้งเตือนเมื่อ
          .large-6.columns
            = f.input :reminder_when, collection: {"Status change" => "status_changed", "Specific post" => "specific_post", "Specific time" => "specific_time"}, selected: @user.reminder_when.to_sym, label: false, disabled: true
        .row
          .large-6.columns ช่่องทางแจ้งเตือน
          .large-6.columns
            = f.input :reminder_by, collection: {"Email" => "email" , "SMS" => "sms"}, selected: @user.reminder_by.to_sym, label: false
            /, "WhatsApp" => "whatsapp", "Facebook Chat" => "facebook"
        .row
          .large-6.columns หมายเลขโทรศัพท์
          .large-6.columns
            = f.input :phone_no, :placeholder => "0812345678", :required => true,  label: false
        .row
          .large-12.columns
            = f.submit 'บันทึก', class: 'button'
    .large-3.columns &nbsp;

= render "shared/required_remider"

app/views/users/edit_customer.html.haml
.row
  .col-lg-12
    .col-lg-3 &nbsp;
    .col-lg-6
      = render 'form_customer', locals: { user: @user }
    .col-lg3 &nbsp;

app/views/users/index.html.haml
.large-12.columns 
  - if current_user.present?
    = current_user.email

app/views/users/user.html.haml
.row
  .col-lg-12
    / /.panel-heading
    .panel-body
      .inbox-checkbox-triggered
        .btn-group.pull-right
          = link_to raw("<i class='glyphicon glyphicon-plus'></i> #{t('backend.add')}"), store_add_customer_url(role: 'admin'), class: 'btn btn-primary'
      .table-responsive
        %table#dataTables.table.table-striped.table-hover.dataTable
          %thead
            %tr
              %th email
              %th name
              %th{width: 150} Phone no.
              %th{width: 150} roles
              %th{width: 250}
          %tbody
            - @users.each_with_index do |u, i|
              - if u.roles.map(&:name).include?('god') then next end
              %tr{class: (i%2==0) ? 'odd' : 'even'}
                %td=u.email
                %td=u.name
                %td=u.phone_no
                %td=u.roles.map(&:name).join(', ')
                %td
                  = pluralize(u.customers.count, 'customer')
                  .btn-group.display-inline.pull-right.text-align-left.hidden-tablet
                    %button.btn.btn-default.txt-color-blue.dropdown-toggle{"data-toggle" => "dropdown"}
                      %i.fa.fa-cog.fa-lg
                    %ul.dropdown-menu.dropdown-menu-xs.pull-right
                      %li
                        %a{href: store_profile_with_path(u)}
                          %i.fa.fa-pencil.fa-lg.fa-fw.txt-color-greenLight
                          = succeed "dit" do
                            %u E
                      %li.divider
                      %li
                        %a{href: "javascript:void(0);"}
                          %i.fa.fa-times.fa-lg.fa-fw.txt-color-red
                          = succeed "elete" do
                            %u D
                      %li.divider
        / /.table-responsive
      / /.panel-body
      = will_paginate @users, :previous_label => t("will_paginate.previous"), :next_label => t("will_paginate.next"), renderer: BootstrapPagination::Rails
    / /.panel
  / /.col-lg-12
= content_for :stylesheets do
  = stylesheet_link_tag 'dataTable.bootstrap'
= content_for :javascripts do
  = javascript_include_tag 'jquery.dataTables', 'dataTable.bootstrap'