config/routes.rb
Pagpos::Application.routes.draw do
  get "statistics/index"
  get "packages/index"
  post "subscriber/create" => "subscribers#create"
  get "store_metadatas/create"
  get "store_metadatas/update"
  get "newsletters/index"
  get "sms/index"
  get "stores/index"
  get "stores/dashboard"
  get 'trackings' => 'trackings#new', as: 'new_tracking'
  get 'tracking/:code/:token' => 'trackings#show', as: 'tracking'
  post 'trackings' => 'trackings#create'
  delete 'tracking/:code/:token' => 'trackings#destroy'

  get 'subscriber' => "welcome#index"
  get 'welcome' => "pagpos#new2"

  get 'about' => 'welcome#about'

  get 'pagpos' => "pagpos#new"
  post 'pagpos' => "pagpos#create"
  get 'pagpos/:code' => "pagpos#show" #, as: "pagpos_result"

  get 'pagpos2' => "pagpos#new2"

  devise_for :users, :controllers => {
    :omniauth_callbacks => "omniauth_callbacks",
    :sessions => "sessions",
    :passwords => "passwords",
    :registrations => "stores"
  }
  # get 'users/auth/facebook' => 'omniauth_callbacks#passthru'
  # get 'users/auth/google' => 'omniauth_callbacks#passthru'
  # get 'users/auth/twitter' => 'omniauth_callbacks#passthru'

  get 'templates' => 'welcome#templates'

  get 'user_agreement' => 'welcome#user_agreement'
  get 'privacy' => 'welcome#privacy'

  devise_scope :user do
    # root to: 'devise/sessions#new'
    # root to: 'welcome#index'
    root to: 'pagpos#new2'
    get 'users' => "users#index"
    put 'users/:id' => 'users#update', as: 'user_update'
    get 'user_profile' => 'users#edit'
    get 'users/auth/:provider' => 'omniauth_callbacks#passthru'

    get 'send_fbchat' => 'api/v1/pagpos#fbchat'

    # namespace :store do
    #   root to: redirect(path: '/store/dashboard')
    #   get 'dashboard' => 'dashboards#index'
    #   get 'sms', shallow: true
    # end

    # namespace :admin do
    #   root to: redirect(path: '/admin/dashboard')
    #   get 'dashboard' => 'dashboard#index'
    # end

    scope shallow_path: "store" do
      get 'store' => redirect(path: '/store/dashboard'), as: 'stores_root'
      get 'store/dashboard' => 'stores#dashboard'
      get 'store/login' => 'stores#index'
      get 'store/register' => 'stores#register'
      post 'store/register' => 'stores#create'
      get 'store/recovery_password' => 'stores#forgot_password'

      get 'store/profile' => 'stores#profile'
      get 'store/profile/:user_id' => 'stores#profile', as: 'store_profile_with'
      patch 'store/profile' => 'stores#update_profile'
      get 'store/lists' => 'stores#list'

      get 'store/sms/packages' => 'sms#packages', as: 'store_campaigns'
      post 'store/sms/packages/(:id)/buy' => 'sms#buy_package', as: 'store_buy_package'
      get 'store/sms/packages/get_free_package' => 'sms#get_free_package', as: 'store_get_free_package'
      # post 'store/sms/packages/(:id)/paid' => 'sms#paid_package', as: 'store_paid_package'
      get 'store/sms/(:filter)' => 'sms#index', as: 'store_sms'
      get 'store/newsletters' => 'newsletters#index'

      get 'store/sms/buy_package/test/callback' => 'sms#buy_package_callback', as: 'store_buy_package_test_callback'
      get 'store/sms/buy_package/live/callback' => 'sms#buy_package_callback', as: 'store_buy_package_live_callback'

      get 'store/customers' => 'users#customer'
      get 'store/add_customer' => 'users#add_customer'
      get 'store/customer/:id' => 'users#detail_customer', as: 'store_customer'
      delete 'store/customer/:id' => 'users#destroy_customer'
      get 'store/customer/:id/edit' => 'users#edit_customer', as: 'store_edit_customer'
      post 'store/customer' => 'users#create_customer'
      patch 'store/customer/:id' => 'users#update_customer'

      get 'store/users' => 'users#user'
      get 'store/packages' => 'packages#index'
      get 'store/statistics' => 'statistics#index'
      get 'store/invoices' => 'pag_invoices#index'
      get 'store/invoices/:payment_code' => 'pag_invoices#show', as: 'store_invoice'
      delete 'store/invoices/:payment_code' => 'pag_invoices#destroy'
    end

  end

  namespace :api do
    namespace :v1  do
      devise_for :users
      root to: 'welcome#index'

      # Trackings always send :code and :token
      get 'trackings/:code/:token' => 'trackings#show', as: 'trackings'
      post 'trackings' => 'trackings#create'
      delete 'trackings' => 'tracking#destroy'

      get 'force_get_data' => 'pagpos#force_get_data'
      get 'show' => 'pagpos#show'
      # get 'auth/:provider' => 'omniauth_callbacks#passthru'
      # get 'auth/facebook' => 'omniauth_callbacks#passthru'
      # get 'auth/google' => 'omniauth_callbacks#passthru'
      # get 'auth/twitter' => 'omniauth_callbacks#passthru'
    end
  end

  mount Resque::Server, :at => "/resque"
  # authenticate :user do
    # mount Resque::Server, :at => "/resque"
  # end


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/views/shared/_flash_message.html.haml
- flash.each do |type, message| 
  %div{class: "alert-box #{type}", "data-alert" => true}
    %a.close{href: '#'} &times;
    = message

app/views/shared/_flash_message_backend.html.haml
- flash.each do |type, message|
  - type = 'danger' if type.eql?(:alert)
  %div{class: "alert alert-#{type} alert-dismissable"}
    %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", :type => "button"} &times;
    = message.class.eql?(String)? message : message.join(', ')
:css
  .alert {
    border-radius: 0;
  }

  .alert-error,
  .alert-box.alert {
    background-color: #C60F13;
    border-color: #970B0E;
    color: #FFFFFF;
  }

  .alert-notice,
  .alert-box {
    background-color: #2BA6CB;
    border-color: #2284A1;
    border-style: solid;
    border-width: 1px;
    color: #FFFFFF;
    display: block;
    font-size: 0.875em;
    font-weight: bold;
    margin-bottom: 1.25em;
    padding: 0.6875em 1.3125em 0.75em 0.6875em;
    position: relative;
  }

  .alert-dismissable .close {
    right: 0;
  }

app/views/shared/_footer.html.haml
%footer
  .row
    .large-12.columns.footer
      .large-10.columns
        %ul.footer_menu
          %li
            = raw(t("footer.copyright", year: Time.now.year))
            / %a{href: "#", style: "font-size:16px; margin-right:15px", title: "twitter"}
            /   %i.foundicon-s-twitter= t('social.twitter')
            / %a{href: "#", style: "font-size:16px; margin-right:15px", title: "facebook"}
            /   %i.foundicon-s-facebook= t('social.facebook')
            / %a{href: "#", style: "font-size:16px; margin-right:15px", title: "pinterest"}
            /   %i.foundicon-s-pinterest
            /   Pinterest
            / %a{href: "#", style: "font-size:16px", title: "instagram"}
            /   %i.foundicon-s-instagram
            /   Instagram
          -# %li
          -#   = link_to t("footer.menu.bug_report"), "#"
          -# %li
          -#   = link_to t("footer.menu.term_of_use"), "#"
          -# %li
          -#   = link_to t("footer.menu.about"), "#"
          -# %li
          -#   = link_to t("footer.menu.contact"), "#"
          -# %li
          -#   = link_to t("footer.menu.store"), store_login_url
      .large-2.columns
        .bizspark_logo
          = image_tag('BizSpark_Startup.jpg')
  / .alpha-version

app/views/shared/_modalbox_credit_card_form_commingsoon.html.haml
.row
  #myModal.modal.fade{"aria-hidden" => "true", "aria-labelledby" => "myModalLabel", :role => "dialog", :tabindex => "-1"}
    .modal-dialog
      .modal-content.envelope
        .modal-header
          %button.close{"aria-hidden" => "true", "data-dismiss" => "modal", :type => "button"} ×
          %h4#myModalLabel.modal-title= t('text.package.payment_info')
        .modal-body
          .block-center.commingsoon
            %span Comming soon.

app/views/shared/_navbar.html.haml
%nav.top-bar
  .large-12.columns.header_nav
    .row
      .large-3.columns &nbsp;
      .large-9.columns
        %ul#menu-header.nav-bar.right
          %li
          - unless current_user.blank?
            %li
              = link_to t('menu.tracking'), new_tracking_path
          - unless current_user.blank?
            %li
              = link_to t('menu.profile'), user_profile_path
          - unless current_user.blank?
            %li
              = link_to t('menu.signout'), destroy_user_session_path, method: :delete
          - if current_user.blank?
            %li
              = link_to t("footer.menu.store"), store_login_url
            -# %li
            -#  = link_to t('menu.find_package'), pagpos_path
            -# %li
            -#   = link_to t('menu.login_with_facebook'), user_omniauth_authorize_path(:facebook)
            -# %li
            -#   = link_to t('menu.signin'), new_user_session_path

app/views/shared/_navbar2.html.haml
%nav.top-bar
  .large-12.columns.header_nav
    .row
      .large-3.columns
        = current_page?(root_url) ? raw('&nbsp;') : link_to(image_tag('logo.png', width: 175), root_path)
      .large-9.columns
        %ul#menu-header.nav-bar.right
          - unless current_user.blank?
            %li
              = link_to t('menu.profile'), user_profile_path
            %li
              = link_to t('menu.signout'), destroy_user_session_path, method: :delete
          - if current_user.blank?
            %li
              = link_to t("footer.menu.about"), about_url
            %li
              = link_to t('menu.login_with_facebook'), user_omniauth_authorize_path(:facebook)
            -# %li
            -#   = link_to t('menu.signin'), new_user_session_path

app/views/shared/_navbar_api.html.haml
.row
  .large-3.columns
    %h1
      %a{ href: "/" }
        %img{src: "http://placehold.it/400x100&text=Logo"}/
  .large-9.columns
    %ul.right.button-group
      %li
        - unless current_user.nil?
          = link_to "Tracking", new_tracking_path
          = link_to "Profile", user_profile_path
          = link_to "Signout", destroy_user_session_path, method: :delete
        - else
          = link_to "Twitter", api_v1_user_omniauth_authorize_path(:twitter)
          = link_to "Google", api_v1_user_omniauth_authorize_path(:google_oauth2)
          = link_to "Facebook", api_v1_user_omniauth_authorize_path(:facebook)
          = link_to "Signin", new_user_session_path
/ End Header and Nav

app/views/shared/_navbar_backend.html.haml
%nav.navbar.navbar-default.navbar-static-top{:role => "navigation", :style => "margin-bottom: 0"}
  .navbar-header= link_to raw("#{image_tag('logos.png', width: 250)}"), root_url, class: "navbar-brand"
  //.navbar-header
  %ul.nav.navbar-top-links.navbar-right
    -# Notification Menu
    -# %li.dropdown
    -#   %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
    -#     %i.fa.fa-bell.fa-fw
    -#     %i.fa.fa-caret-down
    -#   %ul.dropdown-menu.dropdown-alerts
    -#     %li
    -#       %a{:href => "#"}
    -#         %div
    -#           %i.fa.fa-comment.fa-fw
    -#           New Comment
    -#           %span.pull-right.text-muted.small 4 minutes ago
    -#     %li.divider
    -#     %li
    -#       %a{:href => "#"}
    -#         %div
    -#           %i.fa.fa-twitter.fa-fw
    -#           3 New Followers
    -#           %span.pull-right.text-muted.small 12 minutes ago
    -#     %li.divider
    -#     %li
    -#       %a{:href => "#"}
    -#         %div
    -#           %i.fa.fa-envelope.fa-fw
    -#           Message Sent
    -#           %span.pull-right.text-muted.small 4 minutes ago
    -#     %li.divider
    -#     %li
    -#       %a{:href => "#"}
    -#         %div
    -#           %i.fa.fa-tasks.fa-fw
    -#           New Task
    -#           %span.pull-right.text-muted.small 4 minutes ago
    -#     %li.divider
    -#     %li
    -#       %a{:href => "#"}
    -#         %div
    -#           %i.fa.fa-upload.fa-fw
    -#           Server Rebooted
    -#           %span.pull-right.text-muted.small 4 minutes ago
    -#     %li.divider
    -#     %li
    -#       %a.text-center{:href => "#"}
    -#         %strong See All Alerts
    -#         %i.fa.fa-angle-right
    -#   / /.dropdown-alerts
    -# / /.dropdown
    %li.dropdown
      %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
        %i.fa.fa-user.fa-fw
        %i.fa.fa-caret-down
      = menu_builder :profile, :divider, :logout, {id: '', class: 'dropdown-menu dropdown-user'}
      //.dropdown-user
    //.dropdown
  //.navbar-top-links
//.navbar-static-top
%nav.navbar-default.navbar-static-side{:role => "navigation"}
  .sidebar-collapse
    = menu_builder :dashboard, :stores, :campaigns, :sms, :newsletters, :customers, :users, :packages, :statistics, :invoices, {id: 'side-menu', class: 'nav'}
    //#side-menu
  / /.sidebar-collapse
/ /.navbar-static-side

app/views/shared/_required_remider.html.haml
= content_for :javascripts do
  :javascript
    $(document).ready(function(){
      if($('#user_reminder_by').val() == 'sms'){
        $('#user_phone_no').attr('required', 'required');
        $('#user_phone_no, .user_phone_no').addClass('required');
      }
      else if($('#user_reminder_by').val() == 'email'){
        $('#user_email').attr('required', 'required');
        $('#user_email').addClass('required')
      }
      $('#user_reminder_by').on('change', function(){
        if($(this).val() == 'sms'){
          $('#user_phone_no').attr('required', true);
          $('#user_phone_no, .user_phone_no').addClass('required');

          $('#user_email').attr('required', false);
          $('.user_email, #user_email').removeClass('required');
        }
        else if($(this).val() == 'email'){
          $('#user_email').attr('required', 'required');
          $('.user_email, #user_email').addClass('required');

          $('#user_phone_no').attr('required', false);
          $('#user_phone_no, .user_phone_no').removeClass('required');
        }
      });
    });