config/routes.rb
Pagpos::Application.routes.draw do
  get "statistics/index"
  get "packages/index"
  post "subscriber/create" => "subscribers#create"
  get "store_metadatas/create"
  get "store_metadatas/update"
  get "newsletters/index"
  get "sms/index"
  get "stores/index"
  get "stores/dashboard"
  get 'trackings' => 'trackings#new', as: 'new_tracking'
  get 'tracking/:code/:token' => 'trackings#show', as: 'tracking'
  post 'trackings' => 'trackings#create'
  delete 'tracking/:code/:token' => 'trackings#destroy'

  get 'subscriber' => "welcome#index"
  get 'welcome' => "pagpos#new2"

  get 'about' => 'welcome#about'

  get 'pagpos' => "pagpos#new"
  post 'pagpos' => "pagpos#create"
  get 'pagpos/:code' => "pagpos#show" #, as: "pagpos_result"

  get 'pagpos2' => "pagpos#new2"

  devise_for :users, :controllers => {
    :omniauth_callbacks => "omniauth_callbacks",
    :sessions => "sessions",
    :passwords => "passwords",
    :registrations => "stores"
  }
  # get 'users/auth/facebook' => 'omniauth_callbacks#passthru'
  # get 'users/auth/google' => 'omniauth_callbacks#passthru'
  # get 'users/auth/twitter' => 'omniauth_callbacks#passthru'

  get 'templates' => 'welcome#templates'

  get 'user_agreement' => 'welcome#user_agreement'
  get 'privacy' => 'welcome#privacy'

  devise_scope :user do
    # root to: 'devise/sessions#new'
    # root to: 'welcome#index'
    root to: 'pagpos#new2'
    get 'users' => "users#index"
    put 'users/:id' => 'users#update', as: 'user_update'
    get 'user_profile' => 'users#edit'
    get 'users/auth/:provider' => 'omniauth_callbacks#passthru'

    get 'send_fbchat' => 'api/v1/pagpos#fbchat'

    # namespace :store do
    #   root to: redirect(path: '/store/dashboard')
    #   get 'dashboard' => 'dashboards#index'
    #   get 'sms', shallow: true
    # end

    # namespace :admin do
    #   root to: redirect(path: '/admin/dashboard')
    #   get 'dashboard' => 'dashboard#index'
    # end

    scope shallow_path: "store" do
      get 'store' => redirect(path: '/store/dashboard'), as: 'stores_root'
      get 'store/dashboard' => 'stores#dashboard'
      get 'store/login' => 'stores#index'
      get 'store/register' => 'stores#register'
      post 'store/register' => 'stores#create'
      get 'store/recovery_password' => 'stores#forgot_password'

      get 'store/profile' => 'stores#profile'
      get 'store/profile/:user_id' => 'stores#profile', as: 'store_profile_with'
      patch 'store/profile' => 'stores#update_profile'
      get 'store/lists' => 'stores#list'

      get 'store/sms/packages' => 'sms#packages', as: 'store_campaigns'
      post 'store/sms/packages/(:id)/buy' => 'sms#buy_package', as: 'store_buy_package'
      get 'store/sms/packages/get_free_package' => 'sms#get_free_package', as: 'store_get_free_package'
      # post 'store/sms/packages/(:id)/paid' => 'sms#paid_package', as: 'store_paid_package'
      get 'store/sms/(:filter)' => 'sms#index', as: 'store_sms'
      get 'store/newsletters' => 'newsletters#index'

      get 'store/sms/buy_package/test/callback' => 'sms#buy_package_callback', as: 'store_buy_package_test_callback'
      get 'store/sms/buy_package/live/callback' => 'sms#buy_package_callback', as: 'store_buy_package_live_callback'

      get 'store/customers' => 'users#customer'
      get 'store/add_customer' => 'users#add_customer'
      get 'store/customer/:id' => 'users#detail_customer', as: 'store_customer'
      delete 'store/customer/:id' => 'users#destroy_customer'
      get 'store/customer/:id/edit' => 'users#edit_customer', as: 'store_edit_customer'
      post 'store/customer' => 'users#create_customer'
      patch 'store/customer/:id' => 'users#update_customer'

      get 'store/users' => 'users#user'
      get 'store/packages' => 'packages#index'
      get 'store/statistics' => 'statistics#index'
      get 'store/invoices' => 'pag_invoices#index'
      get 'store/invoices/:payment_code' => 'pag_invoices#show', as: 'store_invoice'
      delete 'store/invoices/:payment_code' => 'pag_invoices#destroy'
    end

  end

  namespace :api do
    namespace :v1  do
      devise_for :users
      root to: 'welcome#index'

      # Trackings always send :code and :token
      get 'trackings/:code/:token' => 'trackings#show', as: 'trackings'
      post 'trackings' => 'trackings#create'
      delete 'trackings' => 'tracking#destroy'

      get 'force_get_data' => 'pagpos#force_get_data'
      get 'show' => 'pagpos#show'
      # get 'auth/:provider' => 'omniauth_callbacks#passthru'
      # get 'auth/facebook' => 'omniauth_callbacks#passthru'
      # get 'auth/google' => 'omniauth_callbacks#passthru'
      # get 'auth/twitter' => 'omniauth_callbacks#passthru'
    end
  end

  mount Resque::Server, :at => "/resque"
  # authenticate :user do
    # mount Resque::Server, :at => "/resque"
  # end


  # Example of regular route:
  #   get 'products/:id' => 'catalog#view'

  # Example of named route that can be invoked with purchase_url(id: product.id)
  #   get 'products/:id/purchase' => 'catalog#purchase', as: :purchase

  # Example resource route (maps HTTP verbs to controller actions automatically):
  #   resources :products

  # Example resource route with options:
  #   resources :products do
  #     member do
  #       get 'short'
  #       post 'toggle'
  #     end
  #
  #     collection do
  #       get 'sold'
  #     end
  #   end

  # Example resource route with sub-resources:
  #   resources :products do
  #     resources :comments, :sales
  #     resource :seller
  #   end

  # Example resource route with more complex sub-resources:
  #   resources :products do
  #     resources :comments
  #     resources :sales do
  #       get 'recent', on: :collection
  #     end
  #   end

  # Example resource route with concerns:
  #   concern :toggleable do
  #     post 'toggle'
  #   end
  #   resources :posts, concerns: :toggleable
  #   resources :photos, concerns: :toggleable

  # Example resource route within a namespace:
  #   namespace :admin do
  #     # Directs /admin/products/* to Admin::ProductsController
  #     # (app/controllers/admin/products_controller.rb)
  #     resources :products
  #   end
end

app/controllers/sms_controller.rb
# require 'payment_gateway/payment' #if Rails.env.production? || Rails.env.staging?
# require 'money'
# require 'money/bank/google_currency'

class SmsController < ApplicationController
  before_filter :require_merchant
  before_filter :search_by
  layout 'backend'

  def index
    @credit = 0;
    @sent   = 0;
    @campaigns.each do |cu|
      @credit += cu.campaign.credit
    end

    @credit_used = 0;
    @trackings.each do |t|
      t.packages.each do |p|
        @credit_used += 1 if p.notification
      end
    end

  end

  def packages
    @page_title = I18n.t('page_title.campaigns')
    @got_lite   = current_user.campaigns_users.where(payment_gateway: 'PAGPOS').count > 0
    if @got_lite
      @campaigns  = Campaign.where(:name.ne => "gift")
    else
      @campaigns  = Campaign.all
    end
  end

  def buy_package
  #   @page_title = I18n.t('page_title.buy_package')
  #   @campaign = Campaign.where(id: params[:id]).first
  #   if params[:type].downcase.eql?('visa') || params[:type].downcase.eql?('mastercard')
  #     result = Pagment::Paypal.with_credit_card(validate_require_params)
  #     if result.id.nil? && result.error.present?
  #       flat[:error] = result.error.name + ' has something went wrong'
  #       return redirect_to :packages
  #     else
  #       invoice = current_user.pag_invoices.new
  #       invoice.payment_code = result.id
  #       invoice.description = params[:payment_transaction_description]
  #       if invoice.save
  #         cu = current_user.campaigns_users.new
  #         cu.campaign_id = @campaign.id
  #         cu.payment_gateway = params[:type]
  #         cu.payment_code = result.id
  #         cu.save
  #         return redirect_to store_invoice_url(result.id)
  #       else
  #         flat[:error] = 'Has something went wrong'
  #         return redirect_to :packages
  #       end
  #     end
  #   end
    return redirect_to :index
  end

  def get_free_package
    if current_user.campaigns_users.where(payment_gateway: 'PAGPOS').count == 0
      campaign = Campaign.where(id: params[:id]).first
      invoice = current_user.pag_invoices.new
      invoice.payment_code = "GOTFREE_#{DateTime.now.to_i}_#{params[:id]}"
      invoice.description  = I18n.t('text.get_free_package.description')
      if invoice.save
        cu = current_user.campaigns_users.new
        cu.campaign_id = campaign.id
        cu.payment_gateway = I18n.t('text.get_free_package.gateway')
        cu.payment_code = invoice.payment_code
        cu.save
        return redirect_to store_invoice_url(invoice.payment_code)
      else
        flat[:error] = 'Has something went wrong'
        return redirect_to :packages
      end
    else
      flat[:error] = 'You got free already'
      return redirect_to :packages
    end
  end

  private
   #  def validate_require_params
   #    currency_accepted = ["USD", "GBP", "CAD", "EUR", "JPY"]
   #    require_params = ["intent", "payment_method", "type", "number", "expire_month", "expire_year", "cvv2", "first_name", "last_name", "line1", "city", "state", "postal_code", "country_code", "campaign_name", "campaign_price", "currency", "quantity", "total", "currency", "payment_transaction_description"]
   #    params[:payment_method] = ['visa', 'mastercard'].include?(params[:type]) ? 'credit_card' : 'paypal'
   #    params[:number] = params[:number].class.eql?(Fixnum) ? params[:number] : params[:number].gsub(/\s+/, '').to_i
   #    unless currency_accepted.include?(params[:currency].upcase)
   #      bank = Money::Bank::GoogleCurrency.new
   #      rate = bank.get_rate(:USD, params[:currency].to_sym).to_f
   #      params[:campaign_price]   = params[:campaign_price].to_f / rate
   #      params[:campaign_price]   = Integer(params[:campaign_price] * 100) / Float(100)
   #      params[:currency]   = params[:currency].downcase.eql?('usd') ? params[:currency] : 'USD'
   #    end
   #    params[:total]        = params[:campaign_price] * params[:quantity].to_i
   #    params.delete_if do |param|
   #      !require_params.include?(param.to_s)
   #    end
   # end

    def search_by
      params[:filter] = 'all' unless params[:filter]
      @trackings      = []
      @customer_count = 0;
      @campaigns = current_user.campaigns_users.all
      case params[:filter]
      when 'all'
        current_user.customers.each do |c|
          @trackings += c.trackings.all
        end
      when 'week'
        # @campaigns = current_user.campaigns_users.where(:created_at.gte => DateTime.now.beginning_of_week, :created_at.lte => DateTime.now.end_of_week)
        current_user.customers.each do |c|
          @trackings += c.trackings.where(:created_at.gte => DateTime.now.beginning_of_week, :created_at.lte => DateTime.now.end_of_week)
        end
      when 'month'
        # @campaigns = current_user.campaigns_users.where(:created_at.gte => DateTime.now.beginning_of_month, :created_at.lte => DateTime.now.end_of_month)
        current_user.customers.each do |c|
          @trackings += c.trackings.where(:created_at.gte => DateTime.now.beginning_of_month, :created_at.lte => DateTime.now.end_of_month)
        end
      when '3months'
        # @campaigns = current_user.campaigns_users.where(:created_at.gte => DateTime.now.beginning_of_month, :created_at.lte => DateTime.now.end_of_month.advance(months: +3))
        current_user.customers.each do |c|
          @trackings += c.trackings.where(:created_at.gte => DateTime.now.beginning_of_month, :created_at.lte => DateTime.now.end_of_month.advance(months: +3))
        end
      when '6months'
        # @campaigns = current_user.campaigns_users.where(:created_at.gte => DateTime.now.beginning_of_month, :created_at.lte => DateTime.now.end_of_month.advance(months: +6))
        current_user.customers.each do |c|
          @trackings += c.trackings.where(:created_at.gte => DateTime.now.beginning_of_month, :created_at.lte => DateTime.now.end_of_month.advance(months: +6))
        end
      when 'year'
        # @campaigns = current_user.campaigns_users.where(:created_at.gte => DateTime.now.beginning_of_year, :created_at.lte => DateTime.now.end_of_year)
        current_user.customers.each do |c|
          @trackings += c.trackings.where(:created_at.gte => DateTime.now.beginning_of_year, :created_at.lte => DateTime.now.end_of_year)
        end
      else
        # @campaigns = current_user.campaigns_users.where(:created_at.gte => DateTime.now.beginning_of_day, :created_at.lte => DateTime.now.end_of_day)
        current_user.customers.each do |c|
          @trackings += c.trackings.where(:created_at.gte => DateTime.now.beginning_of_day, :created_at.lte => DateTime.now.end_of_day)
        end
      end
    end
end

app/views/sms/buy_package.html.haml
.row

app/views/sms/index.html.haml
.row
  .col-lg-4
    .panel.panel-default
      .panel-heading.customer-header
        %span.pull-right
          %ul.nav.navbar-right
            %li.dropdown
              %a.dropdown-toggle{"data-toggle" => "dropdown", :href => "#"}
                %i.fa.fa-cog.fa-fw
                %i.fa.fa-caret-down
              = menu_builder :day, :divider, :week, :divider, :month, :divider, :year, {id: '', class: 'dropdown-menu'}

        %span.pull-left
          SMS Analytics
      .panel-body
        .col-lg-12
          %ul.list
            %li.info.text-align-center
              = link_to "ADD CREDIT", store_campaigns_url, class: "btn btn-success btn-lg"
            %li.info.text-align-center
              %h2.text-align-center
                Sent/Credit
                %span.text-primary="#{@credit_used}/#{@credit}"
  / /.col-lg-12
= content_for :javascripts do
  = javascript_include_tag 'charts'

app/views/sms/packages.html.haml
.row
  - @campaigns.each do |c|
    - if @got_lite
      - box_class = "col-xs-12 col-sm-6 col-md-3"
    - else
      - box_class = "col-xs-12 col-sm-4 col-md-2"
    %div{class: "#{box_class}"}
      %div{class: "panel panel-#{c.color} pricing-big price-box"}
        - unless c.name.eql?('gift')
          .modal-comming-soon
            %span Comming soon.
        =# image_tag "ribbon.png", class: 'ribbon' if c.popular
        .panel-heading
          %h3.panel-title
            = c.name
        .panel-body.no-padding.text-align-center
          .the-price
            %h1
              = c.credit
              %span.subscript= c.unit.upcase
            %h1
              #{c.currency_symbold}
              %span.panel-price= c.price.to_i
        .panel-footer.no-padding.text-align-center
          - buy_btn = c.price.to_i == 0 ? 'free_package' : 'buy_package'
          - model_toggle = c.price.to_i == 0 ? '' : 'modal'
          - if c.price.to_i == 0
            = link_to t('backend.button.try').upcase, '#', role: 'button', class: "btn bg-color-#{c.color} txt-color-white btn-block #{buy_btn}", "data-target" => "#myModal", "data-toggle" => "#{model_toggle}", "data-package-id" => c.id
          - else
            = link_to t('backend.button.buy').upcase, '#', role: 'button', class: "btn bg-color-#{c.color} txt-color-white btn-block #{buy_btn}", "data-target" => "#myModal", "data-toggle" => "#{model_toggle}", "data-package-id" => c.id
- if Rails.env.eql?('development')
  = render "shared/modalbox_credit_card_form_commingsoon"
- else
  = render "shared/modalbox_credit_card_form"

= content_for :javascripts do
  :javascript
    $(document).ready( function() {
      $old_package_id = '__PACKAGE_ID__';
      $('#myModal').modal({
        backdrop: true,
        show: false
      });
      $('.free_package').on('click', function(e){
        e.preventDefault();
        $current_package_id = $(this).data('package-id');
        window.location.href = "#{store_get_free_package_path}?id="+$current_package_id;
      });
      $('.buy_package').on('click', function(e){
        e.preventDefault();
        $package_name = $(this).closest('.panel').find('.panel-title').text().trim();
        $package_price = $(this).closest('.panel').find('.panel-price').text().trim();
        $current_package_id = $(this).data('package-id');
        $('#myModal').on('show.bs.modal', function(){
          /*$checkout_form = $(this).find('form#checkout-form');
          $buy_package_url = $checkout_form.attr('action').replace($old_package_id, $current_package_id);
          $checkout_form.attr('action', $buy_package_url);
          $old_package_id = $current_package_id;

          $checkout_form.find('#campaign_name').val($package_name);
          $checkout_form.find('#campaign_price').val($package_price);
          $checkout_form.find('#currency').val('THB');
          $checkout_form.find('#quantity').val(1);
          $checkout_form.find('#payment_transaction_description').val("#{current_user.name} Order "+ $package_name +" at #{DateTime.now}");*/
        });
      });
    } );